import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/coolbeans?invalid_param=1&allowed_param=yes">
          Link: /coolbeans?invalid_param=1&allowed_param=yes
        </Link>
        <a href="/coolbeans?invalid_param=1&allowed_param=yes">
          anchor: /coolbeans?invalid_param=1&allowed_param=yes
        </a>
      </main>
    </div>
  );
}
